# Generated by Django 5.0.2 on 2024-03-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0003_shop_email_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='chipi.shop'),
            preserve_default=False,
        ),
    ]
