# Generated by Django 5.0.2 on 2024-03-25 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0008_favorite'),
        ('users', '0014_alter_address_email_alter_address_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('track', models.CharField(blank=True)),
                ('first_name', models.CharField(max_length=63)),
                ('middle_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('country', models.CharField()),
                ('region', models.CharField()),
                ('city', models.CharField()),
                ('index', models.CharField()),
                ('addr', models.CharField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='chipi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.buyer')),
            ],
        ),
    ]
