# Generated by Django 5.0.2 on 2024-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0012_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
    ]
