# Generated by Django 5.0.2 on 2024-04-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0015_prodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='chipi.prodcategory'),
        ),
    ]
