# Generated by Django 5.0.2 on 2024-04-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0016_product_prodcategory'),
        ('users', '0015_alter_address_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='from_user',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=1, upload_to='reviews/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
