# Generated by Django 5.0.2 on 2024-04-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0017_remove_review_from_user_review_image_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to='reviews/'),
        ),
    ]
