# Generated by Django 5.0.2 on 2024-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0019_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'В сборке'), (3, 'В пути'), (4, 'Ожидает выдачи'), (5, 'Доставлен')], default=0),
        ),
    ]
