# Generated by Django 5.0.2 on 2024-05-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipi', '0020_remove_product_category_alter_order_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
