# Generated by Django 5.0.2 on 2024-03-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
