# Generated by Django 5.0.2 on 2024-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
