# Generated by Django 5.0.2 on 2024-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_buyer_age_alter_buyer_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
