# Generated by Django 5.0.2 on 2024-03-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_buyer_email_alter_buyer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='email',
            new_name='buyer_email',
        ),
    ]
