# Generated by Django 5.0.2 on 2024-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_email_buyer_buyer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_email',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
