# Generated by Django 5.0.2 on 2024-03-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_buyer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
