# Generated by Django 5.0.2 on 2024-03-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_address_email_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='address',
            name='middle_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(),
        ),
    ]
