# Generated by Django 5.0.2 on 2024-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_address_email_alter_address_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='middle_name',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
