# Generated by Django 5.0.2 on 2024-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_address_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='sex',
            field=models.BooleanField(blank=True, choices=[(0, 'Мужской'), (1, 'Женский')], null=True),
        ),
    ]
